### ISSUE TITLE
Test file doesnt work

### ISSUE THREAD

**Issue by da-w-xu** [publicfrank1234/log-fetcher#1]
Hi! I grabbed some text from wikipedia (attached), and tried running a search on it, but it doesnt seem to give me the correct output. Can we fix this?

curl 'http://localhost:4000/logs?filename=/Users/dxu/src/Hearst.txt&entries=1&filter=Hearst'
was not correct for:
[Hearst.txt](https://github.com/publicfrank1234/log-fetcher/files/14059428/Hearst.txt)

**Comment by da-w-xu** [comment]
similarily, filter=newsreel for the file also doesn't seem correct

**Comment by publicfrank1234** [comment]
This is fixed in this [PR](https://github.com/publicfrank1234/log-fetcher/pull/2/files). 

The solution is implemented by changing `remaining = lines.pop()` to `remaining = lines.shift()`. This ensures the correct line is processed in subsequent buffers.

**Comment by da-w-xu** [comment]
thanks @publicfrank1234 , still getting an error when trying 
curl 'http://localhost:4000/logs?filename=/Users/dxu/src/Hearst.txt&entries=3&filter=Hearst'
only returns 2 lines, but should return 3?

**Comment by publicfrank1234** [comment]
Thanks @da-w-xu for checking. 
I forgot to process the remaining chunk after the main loop. 
It is fixed in this [PR](https://github.com/publicfrank1234/log-fetcher/pull/4).
